ANSIBLE_USER: kevin
APPLICATION: plex
work_dir: "/home/{{ ANSIBLE_USER }}"
git_dir: "{{ work_dir }}/{{ APPLICATION }}"
plex_download: https://downloads.plex.tv/plex-media-server-new/1.43.0.10492-121068a07/debian/plexmediaserver_1.43.0.10492-121068a07_amd64.deb
base_file: plexmediaserver.deb
nfs_server: 192.168.11.20