packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
  }
}

locals {
  my_public_key = trimspace(file("~/.ssh/id_rsa.pub"))
}

variable "ssh_password" {
  type      = string
  sensitive = true
  default   = null 
}


variable "proxmox_vmid" {
  type        = string
  description = "The specific VMID from plex inventory. Generated by script"
}

variable "proxmox_api_token_secret" {
  type      = string
  sensitive = true
}

variable "target_app" {
  type    = string
  # No default, must be an argument
}

variable "proxmox_api_url" { type = string }

variable "clone_template_name" {
  type    = string
  default = "debian-trixie-packer" 
}

source "proxmox-clone" "plex-base" {
  proxmox_url = var.proxmox_api_url
  vm_id       = var.proxmox_vmid
  username    = "terraform@pam!main_terraform"
  token       = var.proxmox_api_token_secret
  node    = "pve"
 
  # Template source settings
  clone_vm = var.clone_template_name
  full_clone = true

  # Enable QEMU agent so Packer can query the IP
  qemu_agent = true

  # Target VM settings 
  vm_name = "plex-golden"
  pool     = "Template"

  cores  = 4
  memory = 4096

  ssh_username = "kevin"
  ssh_handshake_attempts = 100
  ssh_timeout  = "15m"
  ssh_private_key_file = "~/.ssh/id_rsa"
}

build {
  sources = ["proxmox-clone.plex-base"]

  # 0: Move disk to local-zfs from NAS
  provisioner "shell-local" {
    inline = [
      "ssh root@pve 'qm move_disk ${var.proxmox_vmid} scsi0 local-zfs --delete'"
    ]
  }

  # 1: Run Ansible playbook
  provisioner "ansible" {
    playbook_file = "./_packer-build.yaml"
    user          = "kevin"
    use_proxy     = false
    ansible_env_vars = [
      "ANSIBLE_ROLES_PATH=./roles",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ]
    # Pass target_app variable
    extra_arguments = [
      "--extra-vars", "target_app=${var.target_app}"
    ]
  }

  # 2: Final Sanitization 
  provisioner "shell" {
    inline = [
      "sudo cloud-init clean --logs",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo cloud-init clean --logs", 
      "sudo rm -f /etc/netplan/*", 
      "sudo truncate -s 0 /etc/machine-id",
      "sudo sync"
    ]
  }
  
  # 3: Copy the disk back from local-zfs to NAS (nfs)
  post-processor "shell-local" {
    inline = [
    "ssh root@pve 'qm move_disk ${var.proxmox_vmid} scsi0 truenas-nfs --delete'"    ]
  }
}